INSERT INTO event_detail_info (id,name,short_name,name_indirect,unique_name,data_type,web_page_id) VALUES
	 (1,'none','none','none','none',2,0),
	 (2,'none','none','none','none',3,0),
	 (3,'none','none','none','none',3,0),
	 (4,'md_event_detail_name_4','md_event_detail_name_4','md_event_detail_name_indirect_4','GoodSleepDay',1,2100003),
	 (5,'md_event_detail_name_5','md_event_detail_name_5','md_event_detail_name_indirect_5','Halloween',1,0),
	 (6,'md_event_detail_name_6','md_event_detail_short_name_6','md_event_detail_name_indirect_6','EeveeWeek',1,0),
	 (7,'md_event_detail_name_7','md_event_detail_name_7','md_event_detail_name_indirect_7','Holiday',1,0),
	 (8,'md_event_detail_name_8','md_event_detail_name_8','md_event_detail_name_indirect_8','NewYear',1,0),
	 (9,'md_event_detail_name_9','md_event_detail_name_9','md_event_detail_name_indirect_9','LapisLazuliLake',1,0),
	 (10,'md_event_detail_name_9','md_event_detail_short_name_9_1','md_event_detail_name_indirect_9','LapisLazuliLake',3,0);
INSERT INTO event_detail_info (id,name,short_name,name_indirect,unique_name,data_type,web_page_id) VALUES
	 (11,'md_event_detail_name_9','md_event_detail_short_name_9_2','md_event_detail_name_indirect_9','LapisLazuliLake',3,0),
	 (12,'md_event_detail_name_5','md_event_detail_name_5','md_event_detail_name_indirect_5','Halloween',3,0),
	 (13,'md_event_detail_name_6','md_event_detail_short_name_6','md_event_detail_name_indirect_6','EeveeWeek',3,0),
	 (14,'md_event_detail_name_7','md_event_detail_name_7','md_event_detail_name_indirect_7','Holiday',3,0),
	 (15,'md_event_detail_name_10','md_event_detail_short_name_10','md_event_detail_name_indirect_10','Valentine',1,0),
	 (16,'md_event_detail_name_10','md_event_detail_short_name_10','md_event_detail_name_indirect_10','Valentine',3,0),
	 (17,'md_event_detail_name_11','md_event_detail_name_11','md_event_detail_name_indirect_11','ElectricWeek',1,0),
	 (18,'md_event_detail_name_11','md_event_detail_short_name_11','md_event_detail_name_indirect_11','ElectricWeek',3,0),
	 (19,'md_event_detail_name_12','md_event_detail_name_12','md_event_detail_name_indirect_12','Raikou',1,0),
	 (20,'md_event_detail_name_12','md_event_detail_short_name_12_1','md_event_detail_name_indirect_12','Raikou',3,0);
INSERT INTO event_detail_info (id,name,short_name,name_indirect,unique_name,data_type,web_page_id) VALUES
	 (21,'md_event_detail_name_12','md_event_detail_short_name_12_2','md_event_detail_name_indirect_12','Raikou',3,0),
	 (22,'md_event_detail_name_12','md_event_detail_name_12','md_event_detail_name_indirect_12','Raikou',4,0),
	 (23,'md_event_detail_name_13','md_event_detail_name_13','md_event_detail_name_indirect_13','FlowerFestival',1,0),
	 (24,'md_event_detail_name_13','md_event_detail_short_name_13','md_event_detail_name_indirect_13','FlowerFestival',3,0),
	 (25,'md_event_detail_name_14','md_event_detail_name_14','md_event_detail_name_indirect_14','FireWeek',1,0),
	 (26,'md_event_detail_name_14','md_event_detail_short_name_14','md_event_detail_name_indirect_14','FireWeek',3,0),
	 (27,'md_event_detail_name_15','md_event_detail_name_15','md_event_detail_name_indirect_15','Entei',1,0),
	 (28,'md_event_detail_name_15','md_event_detail_short_name_15','md_event_detail_name_indirect_15','Entei',3,0),
	 (29,'md_event_detail_name_15','md_event_detail_short_name_15_2','md_event_detail_name_indirect_15','Entei',3,0),
	 (30,'md_event_detail_name_15','md_event_detail_name_15','md_event_detail_name_indirect_15','Entei',4,0);
INSERT INTO event_detail_info (id,name,short_name,name_indirect,unique_name,data_type,web_page_id) VALUES
	 (31,'md_event_detail_name_16','md_event_detail_name_16','md_event_detail_name_indirect_16','SummerFestival',1,0),
	 (32,'md_event_detail_name_16','md_event_detail_short_name_16','md_event_detail_name_indirect_16','SummerFestival',3,0),
	 (33,'md_event_detail_name_17','md_event_detail_name_17','md_event_detail_name_indirect_17','SukusukuWeek',1,1100001),
	 (34,'md_event_detail_name_18','md_event_detail_name_18','md_event_detail_name_indirect_18','1stAnniv',1,1090001),
	 (35,'md_event_detail_name_18','md_event_detail_short_name_18_1','md_event_detail_name_indirect_18','1stAnniv',3,0),
	 (36,'md_event_detail_name_18','md_event_detail_short_name_18_2','md_event_detail_name_indirect_18','1stAnniv',3,0),
	 (37,'md_event_detail_name_19','md_event_detail_name_19','none','WaterWeek',1,1100002),
	 (38,'md_event_detail_name_19','md_event_detail_short_name_19','none','WaterWeek',3,0),
	 (39,'md_event_detail_name_20','md_event_detail_name_20','none','Suicune',1,2000001),
	 (40,'md_event_detail_name_20','md_event_detail_short_name_20_1','none','Suicune',3,0);
INSERT INTO event_detail_info (id,name,short_name,name_indirect,unique_name,data_type,web_page_id) VALUES
	 (41,'md_event_detail_name_20','md_event_detail_short_name_20_2','none','Suicune',3,0),
	 (42,'md_event_detail_name_20','md_event_detail_name_20','none','Suicune',4,0),
	 (43,'md_event_detail_name_21','md_event_detail_short_name_21','none','SleepingFaceDiscover',1,2000002),
	 (44,'md_event_detail_name_22','md_event_detail_short_name_22','none','OldGoldPowerplant',1,2000004),
	 (45,'md_event_detail_name_22','md_event_detail_short_name_22_1','none','OldGoldPowerplant',3,0),
	 (46,'md_event_detail_name_22','md_event_detail_short_name_22_2','none','OldGoldPowerplant',3,0),
	 (47,'md_event_detail_name_5','md_event_detail_name_5','md_event_detail_name_indirect_5','Halloween-2024',1,2100001),
	 (48,'md_event_detail_name_5','md_event_detail_name_5','md_event_detail_name_indirect_5','Halloween-2024',3,0),
	 (49,'md_event_detail_name_6','md_event_detail_short_name_6','md_event_detail_name_indirect_6','EeveeWeek-2024',1,2100002),
	 (50,'md_event_detail_name_6','md_event_detail_short_name_6','md_event_detail_name_indirect_6','EeveeWeek-2024',3,0);
